### ISSUE TITLE
-Crash on latest update-

### ISSUE THREAD

**Issue by ghost** [Aurocosh/divine-favor#1]
https://paste.dimdev.org/peyayavoju.mccrash

This is on the latest update you released a few moments ago, I don't have much other information (Sorry!)

**Comment by Aurocosh** [comment]
Try version 1.0.476 and check if error is fixed

**Comment by ghost** [comment]
https://paste.dimdev.org/riqofazedu.mccrash



I updated and I still got the crash :(


(Sorry - I don't have much more info...)

**Comment by Aurocosh** [comment]
Are you sure you updated? File version in log file is 1.0.474  
       | LC    | divinefavor                 | GRADLE:VERSION-GRADLE:BUILD     | divinefavor-1.0.474.jar                                     | None                                     |

**Comment by ghost** [comment]
I updated and It crashed again, then I read the logs and apparently I ran out of potion IDs. (Maybe a separate issue, not sure if your mod adds potion effects), so I resolved it using the no more potionID conflict mod. Thank you for fixing the initial issue though!

**Comment by Aurocosh** [comment]
Yeah this mod adds lots of potion effects. Thanks for heads up on potion id limit i didn't know about it.
