### ISSUE TITLE
Grimoire Spell List Crash

### ISSUE THREAD

**Issue by Zopffware** [Aurocosh/divine-favor#10]
The game is crashing whenever I try to open the scrolling GUI for the grimoire. This was working fine in 1.0.559. I first experienced the crash in 1.0.570, and it happened again in 1.0.574. I have not tried 1.0.560.

[Latest crash log](https://pastebin.com/8SPH3f5k)

**Comment by Aurocosh** [comment]
Please try version 1.0.604 and check if issue is resolved

**Comment by Zopffware** [comment]
It's no longer crashing in 1.0.604, but now it only shows one talisman and doesn't scroll. The spiral GUI still works fine, though.

**Comment by Aurocosh** [comment]
There is 3 different GUI for a talisman. One is spiral select, second is a scroll GUI on top of screen, and there is also new third GUI which is used to change properties of certain talismans and can show talisman description.
Most likely you are just mixing up scroll GUI with new property GUI. Check your keyboard bindings to make sure you are using correct GUI.
Also you can check it another way. You said only one talisman shows up, hover your mouse over it and if talisman description appears on the right side of the screen then it means this is talisman property GUI and not scroll GUI.

**Comment by Zopffware** [comment]
Ah, I see. That's exactly what it was.
