### ISSUE TITLE
Toadic Jump Not Working

### ISSUE THREAD

**Issue by Zopffware** [Aurocosh/divine-favor#11]
When I cast Toadic Jump, the effect is applied as usual, but my jump height remains at 1 block, where it used to increase to 3 blocks.

**Comment by Aurocosh** [comment]
I am unable to reproduce this bug, also you did not specified the version so i don't know which to check. I tested on 1.0.632 and it worked. Please test again on latest version.

**Comment by Zopffware** [comment]
I believe it was working in 1.0.559 and hasn't worked in any version I've tried since then, including 1.0.570, 1.0.574, and 1.0.624. It still seems to be present for me in 1.0.632 and 1.0.633.

I've now tested it without any other mods installed and it still seems to be present. I'm on Forge 14.23.5.2838, in case that matters.

**Comment by Aurocosh** [comment]
I think i fixed it. It seems to be was consuming wrong type of favor. It is fixed in version 1.0.638.

**Comment by Zopffware** [comment]
Yeah, it's working for me now. Thank you!
