### ISSUE TITLE
Modpack crash during loading with DivineFavor 1.0.635

### ISSUE THREAD

**Issue by Fireztonez** [Aurocosh/divine-favor#13]
Hello,
I just updated DivineFavor to version 1.0.635 and my modpack I'm working on it crash right now during loading. I also try with version 1.0.634 and the same problem exactly occurs.
With version 1.0.633, the modpack seems to freeze during loading, without a real crash... (I did not retry a second time, because I wanted to be able to continue my work and the tests of the modpack ... .) - The last things seen in the logs were Java errors of Divine Favor followed by connection, reconnection of CCI to Streamlabs and streamelements ....

I just started the modpack with version 1.0.632 and I have not had any problem yet. So, seems that the problem is gone in the last beta released today ...

Crash Report: https://gist.github.com/Fireztonez/15490cd55b5b020052e8a19f42767395

The thing if found little strange is the fact the crash report say Java out of memory, but with the memory allocated to the modpack this is pretty mutch impossible, unless somethings take a abnormal quantity of memory...

Version:
DivineFavor: 1.0.635 - 1.0.634 - 1.0.633
Forge: 14.23.5.2838

Fireztonez

**Comment by Aurocosh** [comment]
Looks like my crafting system optimization backfired. I reworked crafting system in 1.0.637. Please check if it fixes the issue.

**Comment by Fireztonez** [comment]
Yes, thank's the issue is fixed now (I tried the version 1.0.643).
Thank's for fixing it soo fast!! don't even have time to see your message and you already post 6 new updates!!
