### ISSUE TITLE
Cross-mod interaction results in world being null during sleep synchronisation

### ISSUE THREAD

**Issue by noobanidus** [Aurocosh/divine-favor#15]
Not sure exactly which mod is causing this client-side crash: https://pastebin.com/6R8RcAPU

Forge: 2838
Divine Favor: 1.0.663

**Comment by Aurocosh** [comment]
I added extra null check, so hopefully it is fixed in 1.0.683.

**Comment by noobanidus** [comment]
Awesome! That'll be great.
