### ISSUE TITLE
Crash in guidebook

### ISSUE THREAD

**Issue by Johannason** [Aurocosh/divine-favor#18]
Most of the guidebook works just fine. Some of the talismans don't have descriptions yet, but that's fine.  
When opening any Arrow Talisman entry, the game immediately freezes and crashes. The error message suggests that it can't find a texture or image...?

**Comment by Aurocosh** [comment]
You did not specified which version you are using. I am pretty sure this error was already fixed in version 1.0.662. Please update and check if it is working.

**Comment by Johannason** [comment]
Ah, fair enough. Was using 1.0.653, the Release version. Will update.

**Comment by Johannason** [comment]
Verified, issue does not occur in 1.0.686.
