### ISSUE TITLE
[Feature request] Json customization for altars

### ISSUE THREAD

**Issue by Alessandro404** [Aurocosh/divine-favor#19]
Hi! I'm building a modpack with a lot of different blocks from other mods.

for balance reason, it would be great if the altar multiblocks were customizable.

They already are json inside the mod jar, but are not replaceable with resource packs or the mod "resources".

**Comment by Aurocosh** [comment]
Added ability to replace default multiblocks with custom one in version 1.0.713.

First, you gonna need to create mutiblock json string. To do so, just build any structure normally in your minecraft world. After it is finished you gonna need an item called "Mystic architect stick". This is creative only item intended for converting in game multiblock structures into json string that mod can use.
You will need to select area where multiblock is located. Selected area is defined by two corners of a cube, right click on first corner, and then right click on second corner. While you holding architect stick in your hand selected area is visible. After you selected area sneak while holding stick and scroll mouse wheel, it will switch architect stick's current mode. Current mode will be written to chat.
There are 4 modes:
- Select multiblock base - In this mode if you sneak right click on any block then you will set this block as multiblock base. Multiblock base is an anchor position of multiblock and is needed for Patchouli. This position is considered origin of mulitiblock.
- Select controller - In this mode if you sneak right click on any block then you will set this block as multiblock controller. Multiblock without a controller is invalid. For altar controller is a medium (Iron medium, gold medium, etc...). For lectern multiblocks controller is a soulbound lectern (Any type).
- Select air block - In this mode if you sneak right click on any block then any blocks of this type in multiblock will be required to be empty spaces. It is not required to do, multiblocks can be created without this.
- Create template - After you selected blocks, set multiblock base and set multiblock controller then switch stick to this mode and sneak right click any block. After you do that the json string for multiblock will be generated and copied to clipboard. You can go ahead and paste it in json file.

After you created json file with multiblock you need to put it in proper place in configs.
Create folder structure like this in minecraft config folder:
config
  - divinefavor
      - custom_multiblocks
          - altar
          - soulbound_lectern

Altar multiblock json files should be placed in altar folder and should have the name of spirit they are belong to. For example neblaze altar json file should be called: neblaze.json .
Lectern multiblock json files should be placed in soulbound_lectern folder and similarly should have the name of spirit they are belong to.

Json files for custom multiblocks should be present both on server and client side. They will not be synchronized from server to client.

**Comment by Aurocosh** [comment]
Here is example config with several custom multiblocks
[config.zip](https://github.com/Aurocosh/divine-favor/files/3411646/config.zip)

**Comment by Aurocosh** [comment]
Also when you create multiblock 'Front' of the multiblock should be facing towards east. It is required for Patchouli. If you don't do that multiblock will still work, just trying to build it with Patchouli will be wonky. Front of multiblock will not be facing towards you when you place it on ground.

**Comment by Alessandro404** [comment]
Thank you. I will try asap and post the result
