### ISSUE TITLE
Soulbound Lectern Crashed Server

### ISSUE THREAD

**Issue by Darkfiend009** [Aurocosh/divine-favor#20]
Server crash occurred when one of my players crafted the Soulbound Lectern. The crash happened when taking the lectern out of the crafting table for the first time.

Here is the crash log:

https://pastebin.com/F46zg42j

Here are quick additional details:
Minecraft Version: 1.12.2
Forge Version: 2838
Divine Favor Version: 1.0.711

**Comment by Aurocosh** [comment]
Thanks for report. Should be fixed in 1.0.717.
