### ISSUE TITLE
[Suggestion] Changes for patchouli guidebook

### ISSUE THREAD

**Issue by UvMidnight** [Aurocosh/divine-favor#22]
Just a few personal suggestions for the patchouli guidebook.

book.json:
- show_progress should be set to false. This tag controls the progress bar on the home page and categories, if it is always full, there's not much of a point of keeping it there. 

Every single entry:
- read_by_default in my opinion should be set to true for every single entry. Having no locked entries means that the unread marker's purpose becomes dubious, it makes the book more unpolished, messes with the ordering, and in my opinion, annoying.

**Comment by Aurocosh** [comment]
Thanks for suggestion. Implemented in version 1.0.735.
