### ISSUE TITLE
Dependency not correctly registered

### ISSUE THREAD

**Issue by Sakata-MC** [Aurocosh/divine-favor#27]
Hey.
Auto Network Lib
is not registered as a dependency in forge.
so you'll just get a random af crash, with no clue as to why.
happened to be doing a lib sweep after updating and adding a few mods, got the crash and didn't recall the library being downloaded so guess I got lucky.

**Comment by Aurocosh** [comment]
Thanks for report. Fixed in version 1.0.748.
