### ISSUE TITLE
Crash when using Loon powers

### ISSUE THREAD

**Issue by Johannason** [Aurocosh/divine-favor#32]
Summoned a few Husks. Used the Follow spell a few times.  
Ticking entity crash, null pointer, when checking if one of my Husks is in a vehicle?

https://pastebin.com/XLky6efF

**Comment by Johannason** [comment]
I'm using Divine Favor .751  
If this is fixed in the latest beta, then I will update and feel sheepish.

**Comment by Aurocosh** [comment]
Thanks for report. Should be fixed now in version 1.0.753.  Check if it works.

**Comment by Johannason** [comment]
Fix confirmed. I didn't notice any husks spawning as chicken-riders in .754, was that the problem?

**Comment by Aurocosh** [comment]
No, the problem was with minion teleportation. When minion ordered to follow you it will teleport to you if you get too far away. Crash was happening when minion can't find spot near you to teleport to. Minion was trying to teleport to position that was null, so i just added extra null check.
