### ISSUE TITLE
How to get all invites?

### ISSUE THREAD

**Issue by ghost** [Aurocosh/divine-favor#34]
The guidebook only contains info for the neblaze invite, was wondering if info for the other invites is available?

**Comment by Aurocosh** [comment]
Guidebook contains info on how to get all invites for all spirits. You only found info about neblaze, so i assume you only read chapter "How to contact a spirit" in category "Basics". This information is provided in this chapter as an example. That is why it only contains info about one spirit. You can find information on how to get invites from other spirits in dedicated category called "Spirits". This category in guidebook contains info about when spirit is active, how to get his invite, how to build spirits altar and what he accepts as offering.

**Comment by qzzz00000** [comment]
Ah, I figured it out, thanks!

**Comment by ghost** [comment]
gotcha, figured it out!
