### ISSUE TITLE
Fatal Error: Ritual Pouch lacks SHIFT+R-click protection

### ISSUE THREAD

**Issue by Shibva** [Aurocosh/divine-favor#37]
Ive had this happen to me twice now; if I sneak over the bundle or use one of the number buttons to swap inventory contents and it is the bundle; the game crashes and the bundle and all item contents are voided.

IM unsure if its a movement optimization mod like Inventory Tweaks causing this to happen but instead of trying to fix that It might be better if you include a slot blacklist to prevent Ritual Pouches in general from being accepted into any of the Ritual Pouch's slots. That would hopefully in turn prevent this issue from happening altogether

**Comment by Aurocosh** [comment]
Fixed in version 1.0.785. It is no longer possible to put Ritual Pouch inside of itself.
