### ISSUE TITLE
Crash on world loading

### ISSUE THREAD

**Issue by Fireztonez** [Aurocosh/divine-favor#4]
Hello,
I want to try Devine Favor but for somes reason I crash each time I try to create a world with the mod installed. I don't know if this is caused by a mod conflict or what, but I just can't load a world with the mod installed.

Crash Report:
https://hastebin.com/riqopowugo

I have add Just Enough ID's into the pack after the first crash because I saw on other issue you add a lot of Potions effect so I want to make sure the crash is not because I used too mutch ID's, but the problem is the same with JustEnoughID's or without JustEnoughID's.

Version:
Minecraft: 1.12.2
Divine Favor: 1.0.478
Forge: 14.23.5.2838
Java: 1.8.0.211

If you need more informations or Log File just let me know.

Fireztonez

**Comment by Aurocosh** [comment]
Hello, please try version 1.0.479 and check if error is fixed.

**Comment by Fireztonez** [comment]
Perfect, look like the problem is fixed now! It work with 1.0.480, thank's
