### ISSUE TITLE
Recipes should accept ore-dictionary

### ISSUE THREAD

**Issue by Fireztonez** [Aurocosh/divine-favor#6]
Hello,
I start working in your mod and I just look the recipes and recipes always used Vanilla material and not the oredictionnary. I think you should accept OreDictionnary for mosts things, question to avoid problem.

Like in somes modpack there have chests and sticks for each type of wood, and this is just a basic example.

So here a list of exaples of recipes how should probably be change to used Ore-Dictionnary for items:
- Immaterial guide; Leather ->ore:leather, bone-> ore:bone,  paper -> ore:paper
- Ender Pumpkin; chest -> ore:chestWood, paper -> ore:paper, Ink Sac -> ore:dyeBlack, Purple Dye->ore:dyePurple
- All Medium blocks: Should accept ore:dyeBlack (And possibly replace blocks by the oredict, but this is not the more important)
- Bone Dagger; Stick->ore:stickWood, stone-> ore:stone, bone-> ore:bone
- Skyfall Talisman; sting -> ore:string, feather, ore:feather, paper -> ore:paper
....

The worst part is clearly the dye, because in modpack, you can have multiples time the same color dye, accepting only vanilla one is just annoying, onless you want to gate somethings question to use only specific thing like Cocoa Beans...

Other example, somes pack, like sevtech have completely remove all Vanilla Dye from the Dye oredict and used Dusts make with that specific color thing to make the Dust Dye... Changing all those whill make simplify a lot the job of somes modpack maker I think (Like me!).

I think changing most of vanilla dye, sticks, chests, paper, feather, leather will make help a lot compatibility in most pack and make your mod even better :D

And, if you can send me the link for the crafttweaker support documentation, I can't find anyware, but you say you have a crtafttweaker support for machines or altar in the mods...

Version: 1.0.501
Thank's
Fireztonez

**Comment by Aurocosh** [comment]
Hello, thanks for the report. This is definitely something that i need to do. Adding ore dictionary to vanilla crafting recipes is easy so i will fix it pretty soon, but adding ore dict to altars may take awhile. At the moment altar crafting does not support ore dictionary, so i will have to rework it.

There is a CraftTweaker support but at the moment there are only two possible actions.

1. Delete default altar recipes for an item
2. Add new altar recipe to item

**Comment by Aurocosh** [comment]
Here is part of mod description that explains how to add and delete recipes:

8) Lots of configurability via config files and CraftTweaker support

With CraftTweeker you can add or remove spirit trading recipes.
You can add new recipe to an altar you need to use following command:
mods.DivineFavor.addMediumRecipe(<minecraft:dirt>,[<divinefavor:calling_stone_arbow>],[<minecraft:grass>, <ore:treeLeaves>]);
First parameter is the result of a recipe. Second is spirits invite, which determines at which spirits altar it can be traded. Third parameter is a list of ingredients. Recipe cannot have more then 7 ingredients.

You can remove existing recipe with following command:

mods.DivineFavor.removeMediumRecipe("divinefavor:arrow_talisman_anti_gravity");
This command accepts item id for item which recipes should not be loaded.

**Comment by Aurocosh** [comment]
mods.DivineFavor.addMediumRecipe(minecraft:dirt,[divinefavor:calling_stone_arbow],[minecraft:grass, ore:treeLeaves]);
I should probably explain this command better. First parameter is result of a recipe. Second is a list of calling stone items. Items in this list determine at which altar this recipe can be traded. In example calling stone of Arbow is used so this recipe can be traded at the altar of Arbow. If more then one calling stone is listed then recipe will be awailable at multiple altars. Last parameter is a list of ingredients.

**Comment by Aurocosh** [comment]
Added support for ore dictionary to altar recipes in version 1.0.514. But ore dictionary ingredient does not support ingredients with more then one items which is messed up almost all recipes. So i made all ingredients require only one item.

**Comment by Aurocosh** [comment]
Regular recipes now also use ore dictionary in version 1.0.516

**Comment by stray-sparks** [comment]
Altars still do not support modded dyes as of 1.0.740. I attempted to trade for a Spell Pick and only bone meal and lapis worked. Same with Minor Regeneration Contract. Spell Bow will only use vanilla light blue dye and bone meal.
