### ISSUE TITLE
Blends being consumed by a bath heater at a very rapid rate on a dedicated server without actually doing anything

### ISSUE THREAD

**Issue by Not-February** [Aurocosh/divine-favor#7]
I tried doing a bath in a single player world to double check, and it appears to be used up much more slowly there - a difference of consuming an entire stack within 10 seconds(dedicated server) versus only consuming one for a longer period of time(single player).

I assume this is not intended behavior given the discrepancy of functionality between singleplayer and multiplayer.

It's... almost like the bath heater is just shoveling more and more of a given blend into the water pool of the bath on the server world - but the blend isn't actually activating in-world despite the bubbles, so it keeps pouring more and more into it. Hopping in the water certainly gives the blend effect in single player, but does absolutely nothing on the server world(except waste copious amounts of blends!)

Currently running version 1.0.511, which I am aware is not the most recent version - however I didn't see anything about this in the changelogs(apologies if I missed it) and it will take more time to be able to test whether it's an 'outdated version multiplayer specific' thing on the server's end(since I need to discuss with the person who manages the server files). If this is something that you would like me to test more on before asking about it again, I will try to get a more up-to-date test done within the next day or so.

EDIT 1: I realize I was mistaken about the bubbles indicating the blend is working, I see now it just means the bath is being heated - but the behavior discrepancy between a single player world and on a dedicated server still seems odd. Will be looking into it more with the latest version.

**Comment by Aurocosh** [comment]
Unfortunately i am unable to reproduce this issue. Bath heater consumes blends at equal rates both on dedicated server and in single player. Are you using any other mods? If so then can you try testing it with Divine Favor alone to make sure it is not caused by a conflict with other mod.

**Comment by Not-February** [comment]
I'm not sure what even changed(if anything), but it actually seems to be working now. The only thing I can think of is that I may have put the fuel in before the blend the first time... but that doesn't seem to be doing it now, either. Using a modded fuel, perhaps? I'm stumped.

**Comment by Not-February** [comment]
Discovered something odd - using a stack of Redstone Blends that I crafted in survival mode will still cause them to be rapidly consumed, but ones cheated in from creative/JEI item list do NOT suffer from this issue. I'll test with another blend soon.

EDIT: I put some wild blend into the bath instead, and it started applying the redstone blend that had been consumed rapidly earlier...? I'm really not sure exactly what is going on.

**Comment by Aurocosh** [comment]
I fixed rapid consumption of blends in version 1.0.535. Please check if issue is resolved.
