### ISSUE TITLE
Can't Open Grimoire

### ISSUE THREAD

**Issue by Zopffware** [Aurocosh/divine-favor#9]
After first getting into this mod and constructing an altar to Redwind, I decided to start by trading for a spell bow and a grimoire. The spell bow seems to function just as expected, but I don't seem to be able to put any talismans into the grimoire.
When I shift + right click as the guide says, and I'm not looking at any blocks, the book moves down out of my field of view and back again, as though something happened, but the GUI that I assume is supposed to appear for me to put my talismans into doesn't appear. If I am looking at a block when I shift click, nothing happens at all.
I still seem to be able to select/use the talismans that are in the grimoire just fine, but that's not much consolation when I can't put them in in the first place.

**Comment by Zopffware** [comment]
Oh, and this is in 1.0.558, if it matters.

**Comment by Aurocosh** [comment]
Thanks for report. Fixed in version 1.0.559
